/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Fri Sep 20 10:51:05 2019. */

#include "simpleNano.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t nanoPB_simpleNano_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, nanoPB_simpleNano, a, a, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, nanoPB_simpleNano, b, a, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
